//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cactuses.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id_history { get; set; }
        public Nullable<int> id_Vistavka { get; set; }
        public Nullable<int> id_cactus { get; set; }
    
        public virtual Cactusi Cactusi { get; set; }
        public virtual Vistavki Vistavki { get; set; }
    }
}
